more general bash options in `bash_funcs`
now doing `set -o pipefail` (which necessitated a few changes in various `termstart`s)
now using extended globbing
not yet using `bash -e`, as so far it causes more problems than it fixes
-	but I hope to get to the point where I can enable this eventually
-	it's sort of the bash equivalent of `use autodie ':all'` in Perl

diff --git a/bin/bash_funcs b/bin/bash_funcs
--- a/bin/bash_funcs
+++ b/bin/bash_funcs
@@ -5,7 +5,16 @@
 
 
 
+###########
+## SETUP ##
+###########
+
+#set -e                                              					# if any command fails, exit the script
+set -o pipefail                                     					# even if it's the first command in a pipeline
+shopt -s extglob                                    					# and allow us to use extended glob patterns
+
 readonly me=${0##*/}													# slightly prettier than $0
+
 
 # I hate that I can't just use an alias here ...
 function vc { ~/proj/VCtools/bin/vc "$@" ; }							# in case we need to get to vc
@@ -25,6 +34,11 @@ do
         done
     fi
 done
+
+
+###########
+## FUNCS ##
+###########
 
 
 function die
