greatly expand the powers of `bash fix_perms`
it can now:
-	detect those bogus files that either Synology or Resilio keeps restoring
--		(even though I never asked it to)
-	detect and fix `git` errors caused by the above landing in `.git/` in very problematic locations
-	ensure that syncing permissions are correct using the new version of `syfixperms`
also, can call it via new alias `fix`
-	this only calls `bash fix_perms` if you happen to be in `~/common/`
-	elsewhere, it currently just throws an error
-	but perhaps someday it can fix different dirs using different methods
ancillary changes:
-	fix_perms:
--		add comment headers for better organization
-	sygit-fixperms:
--		add `set -euo pipefail` to enforce safer `bash` code
--		make it not say anytyhing if there's nothing to fix

diff --git a/bin/sygit-fixperms b/bin/sygit-fixperms
--- a/bin/sygit-fixperms
+++ b/bin/sygit-fixperms
@@ -1,21 +1,26 @@
 #! /bin/bash
+set -euo pipefail
 source ~/common/functions
 
-(
-	echo "potential problem files:"
-	git diff --summary
-) | $PAGER
-
-if confirm "should I try to fix all those?"
+output=$(git diff --summary)
+if [[ $output ]]
 then
-	git diff --summary | perl -lne '
-		# mode change 100755 => 100644 local/absalom/bin/backup
-		if ( /mode change (\d+) => (\d+) (.*)/ )
-		{
-			my ($old, $new, $file) = ($1,$2,$3);
-			$old =~ s/^\d\d//;
-			print "chmod $old $file";
-			chmod(oct($old), $file) == 1 or die("cannot change mode: $old => $file");
-		}
-	'
+	(
+		echo "potential problem files:"
+		echo "$output"
+	) | $PAGER
+
+	if confirm "should I try to fix all those?"
+	then
+		echo "$output" | perl -lne '
+			# mode change 100755 => 100644 local/absalom/bin/backup
+			if ( /mode change (\d+) => (\d+) (.*)/ )
+			{
+				my ($old, $new, $file) = ($1,$2,$3);
+				$old =~ s/^\d\d//;
+				print "chmod $old $file";
+				chmod(oct($old), $file) == 1 or die("cannot change mode: $old => $file");
+			}
+		'
+	fi
 fi
