revamp `fix-network` (esp `fix-network --as-service`)
with the help of ChatGPT:
-	make detection of "eth0" much smarter
--		(also: only do it once, as it's moderately inefficient)
--		(also also: if you can't figure it out, die instead of just returning undefined
-	don't assume the network is down just because DNS is fucked
ancillary changes:
-	reduce amount of time between connectivity checks
-	if network appears down, try again a few times
--		(this helps ensure that it's really really down before restarting everything)
-	consolidate "print message and die" into a `die` function
-	use brace expansion rather than shelling out to `seq`
--		(much more efficient, which is useful now that it's running way more often)
-	fix help message

diff --git a/root/sbin/fix-network b/root/sbin/fix-network
--- a/root/sbin/fix-network
+++ b/root/sbin/fix-network
@@ -1,7 +1,7 @@
 #! /bin/bash
 
 
-SERVICE_CHECKS_EVERY=30								# seconds
+SERVICE_CHECKS_EVERY=10								# seconds
 
 
 readonly ME=${0##*/}
@@ -14,10 +14,11 @@ usage: $ME [--manager] [--eth0] [--kernel-mod]
     --manager       : bounce Network Manager
     --eth0          : bounce eth0 interface (or equivalent)
     --driver        : bounce network card driver (kernel module)
+    --as-service    : run continuously as a service
     --help          : this help message
 
-				things are bounced in the order shown above
-				default: --manager --eth0 --driver
+                things are bounced in the order shown above
+                default: --manager --eth0 --driver
 EOM
 }
 
@@ -58,25 +59,42 @@ then
 fi
 
 
+# throw a message, then exit with an error code
+function die
+{
+	local msg=$1
+	if $as_service
+	then
+		logger -t $ME "$1"
+	else
+		echo "$1" >&2
+	fi
+	exit 1
+}
+
+
 # determine the wired interface
 # it used to always be eth0, but nowadays, not so much
 function eth0
 {
-	for interface in $(ifconfig -s -a | awk 'NR > 1 {print $1}')
+	for interface in $(ip link show | grep 'state UP' | awk '{print $2}' | sed 's/://')
 	do
-		if ethtool $interface 2>/dev/null | grep -q "Supported ports"
+		# verify that the interface has an IP address assigned
+		if ip addr show $interface | grep -q 'inet '
 		then
 			echo $interface
-			break
+			return 0
 		fi
 	done
+	die "cannot determine ethernet interface"
 }
 
 
 # figure out whether we're going to connect or not
 function network-up
 {
-	ping -c 1 google.com > /dev/null 2>&1
+	GOOGLE_DNS=8.8.8.8
+	ping -c 1 $GOOGLE_DNS >/dev/null 2>&1
 }
 
 # check for being up; exit cleanly if we are
@@ -101,10 +119,20 @@ function progress-msg
 }
 
 
-if $as_service && network-up
+if $as_service
 then
-	sleep $SERVICE_CHECKS_EVERY
-	exec $ME --as-service
+	if network-up
+	then
+		sleep $SERVICE_CHECKS_EVERY
+		exec $ME --as-service
+	else
+		# give it a few more chances to be okay
+		for n in {1..5}
+		do
+			sleep 1
+			exit-if-network-up
+		done
+	fi
 fi
 
 if $manager
@@ -119,7 +147,7 @@ then
 	fi
 
 	progress-msg "waiting for reconnect "
-	for n in $(seq 1 20)
+	for n in {1..20}
 	do
 		progress-msg "."
 		sleep 1
@@ -133,10 +161,11 @@ then
 	# this is a bit more intrusive,
 	# but fixes some things the above doesn't
 	progress-msg "\ngoing deeper "
-	ip link set $(eth0) down
-	ip link set $(eth0) up
+	if=$(eth0)
+	ip link set $if down
+	ip link set $if up
 
-	for n in $(seq 1 20)
+	for n in {1..20}
 	do
 		progress-msg "."
 		sleep 1
@@ -158,10 +187,4 @@ then
 	exit-if-network-up "reloaded network kernel mod"
 fi
 
-if $as_service
-then
-	logger -t $ME "failed to restart network"
-else
-	echo "out of tricks"
-fi
-exit 1
+die "failed to restart network"
